{
  "records": {
    "2018-11-07T00:00:00-08:00": [
      {
        "count": 1,
        "date": "2018-11-07T00:00:36.364641-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 184,
        "msg": "Automated push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 8,
        "date": "2018-11-07T07:23:22.847517-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-07T18:07:36.874084-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 184,
        "msg": "Manual push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-07T18:08:09.655944-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 172,
        "msg": "Fetched latest changes.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-07T18:08:24.848219-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 289,
        "msg": "Restarted fairylab.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-07T18:08:25.377682-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded exports.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-07T18:08:25.562699-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded gameday.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-07T18:08:25.680364-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded git.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-07T18:08:25.802051-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded leaguefile.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-07T18:08:25.924268-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded recap.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-07T18:08:27.108139-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded snacks.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-07T18:08:27.230598-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded statsplus.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      }
    ],
    "2018-11-08T00:00:00-08:00": [
      {
        "count": 1,
        "date": "2018-11-08T00:48:27.197797-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 289,
        "msg": "Restarted fairylab.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T00:48:27.742903-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded exports.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T00:48:27.965658-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded gameday.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T00:48:28.092711-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded git.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T00:48:28.223474-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded leaguefile.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T00:48:28.355633-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded recap.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T00:48:29.594560-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded snacks.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T00:48:29.754083-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded statsplus.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T01:12:35.775267-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 289,
        "msg": "Restarted fairylab.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T01:12:36.336003-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded exports.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T01:12:36.565814-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded gameday.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T01:12:36.700007-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded git.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T01:12:36.914546-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded leaguefile.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T01:12:37.255918-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded recap.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T01:12:38.532455-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded snacks.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T01:12:38.672030-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded statsplus.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T18:31:38.055281-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 195,
        "msg": "Tracker locked.",
        "pathname": "/home/pi/filefairy/plugin/exports/exports.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T19:31:32.884741-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 154,
        "msg": "Sim in progress.",
        "pathname": "/home/pi/filefairy/plugin/statsplus/statsplus.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T21:00:25.880856-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 104,
        "msg": "Upload started.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T21:06:59.392510-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 312,
        "msg": "File is up.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T21:07:00.865500-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 306,
        "msg": "Download started.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T21:17:44.050156-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 288,
        "msg": "Download finished.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T21:17:44.560671-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 63,
        "msg": "News updated.",
        "pathname": "/home/pi/filefairy/plugin/recap/recap.py"
      }
    ],
    "2018-11-09T00:00:00-08:00": [
      {
        "count": 1,
        "date": "2018-11-09T00:00:22.374700-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 184,
        "msg": "Automated push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-09T02:17:36.677040-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 289,
        "msg": "Restarted fairylab.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-09T02:17:37.234656-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded exports.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-09T02:17:37.476879-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded gameday.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-09T02:17:37.608755-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded git.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-09T02:17:37.741790-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded leaguefile.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-09T02:17:37.876284-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded recap.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-09T02:17:40.045357-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded snacks.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-09T02:17:40.184540-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded statsplus.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-09T03:23:55.194165-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 172,
        "msg": "Fetched latest changes.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-09T10:24:00.444320-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 172,
        "msg": "Fetched latest changes.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-09T23:28:48.128539-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 184,
        "msg": "Manual push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-09T23:30:08.094690-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 172,
        "msg": "Fetched latest changes.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      }
    ],
    "2018-11-10T00:00:00-08:00": [
      {
        "count": 1,
        "date": "2018-11-10T00:01:02.040908-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 184,
        "msg": "Automated push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T00:07:20.351935-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 172,
        "msg": "Fetched latest changes.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T00:07:36.379087-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 289,
        "msg": "Restarted fairylab.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T00:07:37.046093-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded exports.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T00:07:37.266980-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded gameday.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T00:07:37.401215-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded git.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T00:07:37.544950-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded leaguefile.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T00:07:37.694438-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded recap.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T00:07:38.896202-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded snacks.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T00:07:39.050419-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded statsplus.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T15:02:11.848496-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 205,
        "msg": "Tracker locked.",
        "pathname": "/home/pi/filefairy/plugin/exports/exports.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T17:18:24.379231-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 158,
        "msg": "Sim in progress.",
        "pathname": "/home/pi/filefairy/plugin/statsplus/statsplus.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T18:50:24.828547-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 106,
        "msg": "Upload started.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T18:59:15.184387-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 317,
        "msg": "File is up.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 2,
        "date": "2018-11-10T19:03:40.543099-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 311,
        "msg": "Download started.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T19:03:10.813378-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 299,
        "msg": "Download failed.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T19:09:51.567769-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 293,
        "msg": "Download finished.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T19:09:52.303934-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 64,
        "msg": "News updated.",
        "pathname": "/home/pi/filefairy/plugin/recap/recap.py"
      }
    ],
    "2018-11-11T00:00:00-08:00": [
      {
        "count": 1,
        "date": "2018-11-11T00:01:06.603804-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 186,
        "msg": "Automated push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-11T21:01:33.543411-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 186,
        "msg": "Manual push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-11T23:08:37.868513-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 289,
        "msg": "Restarted fairylab.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-11T23:08:38.574140-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded exports.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-11T23:08:38.804071-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded gameday.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-11T23:08:38.944123-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded git.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-11T23:08:39.108934-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded leaguefile.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-11T23:08:39.255619-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded recap.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-11T23:08:41.063565-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded snacks.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-11T23:08:41.204719-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded statsplus.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      }
    ],
    "2018-11-12T00:00:00-08:00": [
      {
        "count": 1,
        "date": "2018-11-12T00:00:29.871537-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 186,
        "msg": "Automated push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      }
    ],
    "2018-11-13T00:00:00-08:00": [
      {
        "count": 1,
        "date": "2018-11-13T00:00:56.704470-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 186,
        "msg": "Automated push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-13T04:56:19.177377-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 3,
        "date": "2018-11-13T06:34:33.829524-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-13T06:55:27.456494-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-13T07:48:12.462762-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-13T13:03:40.813628-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-13T15:35:16.151007-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 205,
        "msg": "Tracker locked.",
        "pathname": "/home/pi/filefairy/plugin/exports/exports.py"
      },
      {
        "count": 1,
        "date": "2018-11-13T16:00:32.191012-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-13T16:23:29.191515-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 158,
        "msg": "Sim in progress.",
        "pathname": "/home/pi/filefairy/plugin/statsplus/statsplus.py"
      },
      {
        "count": 66,
        "date": "2018-11-13T18:39:40.831971-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/home/pi/filefairy/util/statslab/statslab.py\", line 380, in parse_game_data\n    during=d)))\n  File \"/home/pi/filefairy/util/statslab/statslab.py\", line 140, in _value\n    bat = batters[batting]\nKeyError: ''",
        "levelname": "WARNING",
        "lineno": 488,
        "msg": "Unable to parse https://orangeandblueleaguebaseball.com/StatsLab/reports/news/html/game_logs/log_2164.html.",
        "pathname": "/home/pi/filefairy/util/statslab/statslab.py"
      },
      {
        "count": 67,
        "date": "2018-11-13T18:40:00.022601-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/home/pi/filefairy/util/statslab/statslab.py\", line 380, in parse_game_data\n    during=d)))\n  File \"/home/pi/filefairy/util/statslab/statslab.py\", line 140, in _value\n    bat = batters[batting]\nKeyError: ''",
        "levelname": "WARNING",
        "lineno": 488,
        "msg": "Unable to parse https://orangeandblueleaguebaseball.com/StatsLab/reports/news/html/game_logs/log_2184.html.",
        "pathname": "/home/pi/filefairy/util/statslab/statslab.py"
      },
      {
        "count": 1,
        "date": "2018-11-13T16:34:06.834437-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/home/pi/filefairy/util/urllib_/urllib_.py\", line 16, in urlopen\n    return f.read()\n  File \"/usr/lib/python3.5/http/client.py\", line 461, in read\n    s = self._safe_read(self.length)\n  File \"/usr/lib/python3.5/http/client.py\", line 607, in _safe_read\n    chunk = self.fp.read(min(amt, MAXAMOUNT))\n  File \"/usr/lib/python3.5/socket.py\", line 576, in readinto\n    return self._sock.recv_into(b)\n  File \"/usr/lib/python3.5/ssl.py\", line 937, in recv_into\n    return self.read(nbytes, buffer)\n  File \"/usr/lib/python3.5/ssl.py\", line 799, in read\n    return self._sslobj.read(len, buffer)\n  File \"/usr/lib/python3.5/ssl.py\", line 583, in read\n    v = self._sslobj.read(len, buffer)\nsocket.timeout: The read operation timed out",
        "levelname": "WARNING",
        "lineno": 22,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/urllib_/urllib_.py"
      },
      {
        "count": 15,
        "date": "2018-11-13T17:10:11.505046-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1254, in do_open\n    h.request(req.get_method(), req.selector, req.data, headers)\n  File \"/usr/lib/python3.5/http/client.py\", line 1107, in request\n    self._send_request(method, url, body, headers)\n  File \"/usr/lib/python3.5/http/client.py\", line 1152, in _send_request\n    self.endheaders(body)\n  File \"/usr/lib/python3.5/http/client.py\", line 1103, in endheaders\n    self._send_output(message_body)\n  File \"/usr/lib/python3.5/http/client.py\", line 934, in _send_output\n    self.send(msg)\n  File \"/usr/lib/python3.5/http/client.py\", line 877, in send\n    self.connect()\n  File \"/usr/lib/python3.5/http/client.py\", line 1261, in connect\n    server_hostname=server_hostname)\n  File \"/usr/lib/python3.5/ssl.py\", line 385, in wrap_socket\n    _context=self)\n  File \"/usr/lib/python3.5/ssl.py\", line 760, in __init__\n    self.do_handshake()\n  File \"/usr/lib/python3.5/ssl.py\", line 996, in do_handshake\n    self._sslobj.do_handshake()\n  File \"/usr/lib/python3.5/ssl.py\", line 641, in do_handshake\n    self._sslobj.do_handshake()\nsocket.timeout: _ssl.c:704: The handshake operation timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/urllib_/urllib_.py\", line 15, in urlopen\n    with request.urlopen(url, data=data, timeout=8) as f:\n  File \"/usr/lib/python3.5/urllib/request.py\", line 163, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 466, in open\n    response = self._open(req, data)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 484, in _open\n    '_open', req)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 444, in _call_chain\n    result = func(*args)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1297, in https_open\n    context=self._context, check_hostname=self._check_hostname)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1256, in do_open\n    raise URLError(err)\nurllib.error.URLError: <urlopen error _ssl.c:704: The handshake operation timed out>",
        "levelname": "WARNING",
        "lineno": 22,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/urllib_/urllib_.py"
      },
      {
        "count": 3,
        "date": "2018-11-13T17:10:40.449082-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/home/pi/filefairy/util/urllib_/urllib_.py\", line 16, in urlopen\n    return f.read()\n  File \"/usr/lib/python3.5/http/client.py\", line 461, in read\n    s = self._safe_read(self.length)\n  File \"/usr/lib/python3.5/http/client.py\", line 607, in _safe_read\n    chunk = self.fp.read(min(amt, MAXAMOUNT))\n  File \"/usr/lib/python3.5/socket.py\", line 576, in readinto\n    return self._sock.recv_into(b)\n  File \"/usr/lib/python3.5/ssl.py\", line 937, in recv_into\n    return self.read(nbytes, buffer)\n  File \"/usr/lib/python3.5/ssl.py\", line 799, in read\n    return self._sslobj.read(len, buffer)\n  File \"/usr/lib/python3.5/ssl.py\", line 583, in read\n    v = self._sslobj.read(len, buffer)\nsocket.timeout: The read operation timed out",
        "levelname": "WARNING",
        "lineno": 22,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/urllib_/urllib_.py"
      },
      {
        "count": 8,
        "date": "2018-11-13T17:47:40.203535-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 50,
        "date": "2018-11-13T18:39:33.780774-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/home/pi/filefairy/util/statslab/statslab.py\", line 380, in parse_game_data\n    during=d)))\n  File \"/home/pi/filefairy/util/statslab/statslab.py\", line 140, in _value\n    bat = batters[batting]\nKeyError: ''",
        "levelname": "WARNING",
        "lineno": 488,
        "msg": "Unable to parse https://orangeandblueleaguebaseball.com/StatsLab/reports/news/html/game_logs/log_2218.html.",
        "pathname": "/home/pi/filefairy/util/statslab/statslab.py"
      },
      {
        "count": 17,
        "date": "2018-11-13T18:40:21.334045-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/home/pi/filefairy/util/urllib_/urllib_.py\", line 16, in urlopen\n    return f.read()\n  File \"/usr/lib/python3.5/http/client.py\", line 461, in read\n    s = self._safe_read(self.length)\n  File \"/usr/lib/python3.5/http/client.py\", line 607, in _safe_read\n    chunk = self.fp.read(min(amt, MAXAMOUNT))\n  File \"/usr/lib/python3.5/socket.py\", line 576, in readinto\n    return self._sock.recv_into(b)\n  File \"/usr/lib/python3.5/ssl.py\", line 937, in recv_into\n    return self.read(nbytes, buffer)\n  File \"/usr/lib/python3.5/ssl.py\", line 799, in read\n    return self._sslobj.read(len, buffer)\n  File \"/usr/lib/python3.5/ssl.py\", line 583, in read\n    v = self._sslobj.read(len, buffer)\nsocket.timeout: The read operation timed out",
        "levelname": "WARNING",
        "lineno": 22,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/urllib_/urllib_.py"
      },
      {
        "count": 2,
        "date": "2018-11-13T17:51:04.789098-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1254, in do_open\n    h.request(req.get_method(), req.selector, req.data, headers)\n  File \"/usr/lib/python3.5/http/client.py\", line 1107, in request\n    self._send_request(method, url, body, headers)\n  File \"/usr/lib/python3.5/http/client.py\", line 1152, in _send_request\n    self.endheaders(body)\n  File \"/usr/lib/python3.5/http/client.py\", line 1103, in endheaders\n    self._send_output(message_body)\n  File \"/usr/lib/python3.5/http/client.py\", line 934, in _send_output\n    self.send(msg)\n  File \"/usr/lib/python3.5/http/client.py\", line 877, in send\n    self.connect()\n  File \"/usr/lib/python3.5/http/client.py\", line 1261, in connect\n    server_hostname=server_hostname)\n  File \"/usr/lib/python3.5/ssl.py\", line 385, in wrap_socket\n    _context=self)\n  File \"/usr/lib/python3.5/ssl.py\", line 760, in __init__\n    self.do_handshake()\n  File \"/usr/lib/python3.5/ssl.py\", line 996, in do_handshake\n    self._sslobj.do_handshake()\n  File \"/usr/lib/python3.5/ssl.py\", line 641, in do_handshake\n    self._sslobj.do_handshake()\nsocket.timeout: _ssl.c:704: The handshake operation timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/urllib_/urllib_.py\", line 15, in urlopen\n    with request.urlopen(url, data=data, timeout=8) as f:\n  File \"/usr/lib/python3.5/urllib/request.py\", line 163, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 466, in open\n    response = self._open(req, data)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 484, in _open\n    '_open', req)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 444, in _call_chain\n    result = func(*args)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1297, in https_open\n    context=self._context, check_hostname=self._check_hostname)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1256, in do_open\n    raise URLError(err)\nurllib.error.URLError: <urlopen error _ssl.c:704: The handshake operation timed out>",
        "levelname": "WARNING",
        "lineno": 22,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/urllib_/urllib_.py"
      },
      {
        "count": 1,
        "date": "2018-11-13T17:43:38.672196-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/home/pi/filefairy/util/urllib_/urllib_.py\", line 15, in urlopen\n    with request.urlopen(url, data=data, timeout=8) as f:\n  File \"/usr/lib/python3.5/urllib/request.py\", line 163, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 466, in open\n    response = self._open(req, data)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 484, in _open\n    '_open', req)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 444, in _call_chain\n    result = func(*args)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1297, in https_open\n    context=self._context, check_hostname=self._check_hostname)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1257, in do_open\n    r = h.getresponse()\n  File \"/usr/lib/python3.5/http/client.py\", line 1198, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.5/http/client.py\", line 297, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.5/http/client.py\", line 258, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"/usr/lib/python3.5/socket.py\", line 576, in readinto\n    return self._sock.recv_into(b)\n  File \"/usr/lib/python3.5/ssl.py\", line 937, in recv_into\n    return self.read(nbytes, buffer)\n  File \"/usr/lib/python3.5/ssl.py\", line 799, in read\n    return self._sslobj.read(len, buffer)\n  File \"/usr/lib/python3.5/ssl.py\", line 583, in read\n    v = self._sslobj.read(len, buffer)\nsocket.timeout: The read operation timed out",
        "levelname": "WARNING",
        "lineno": 22,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/urllib_/urllib_.py"
      },
      {
        "count": 1,
        "date": "2018-11-13T17:59:23.624388-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 106,
        "msg": "Upload started.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-13T18:05:07.937013-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-13T18:06:12.000877-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 317,
        "msg": "File is up.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-13T18:06:13.547550-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 311,
        "msg": "Download started.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 5,
        "date": "2018-11-13T18:44:28.353010-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1254, in do_open\n    h.request(req.get_method(), req.selector, req.data, headers)\n  File \"/usr/lib/python3.5/http/client.py\", line 1107, in request\n    self._send_request(method, url, body, headers)\n  File \"/usr/lib/python3.5/http/client.py\", line 1152, in _send_request\n    self.endheaders(body)\n  File \"/usr/lib/python3.5/http/client.py\", line 1103, in endheaders\n    self._send_output(message_body)\n  File \"/usr/lib/python3.5/http/client.py\", line 934, in _send_output\n    self.send(msg)\n  File \"/usr/lib/python3.5/http/client.py\", line 877, in send\n    self.connect()\n  File \"/usr/lib/python3.5/http/client.py\", line 1261, in connect\n    server_hostname=server_hostname)\n  File \"/usr/lib/python3.5/ssl.py\", line 385, in wrap_socket\n    _context=self)\n  File \"/usr/lib/python3.5/ssl.py\", line 760, in __init__\n    self.do_handshake()\n  File \"/usr/lib/python3.5/ssl.py\", line 996, in do_handshake\n    self._sslobj.do_handshake()\n  File \"/usr/lib/python3.5/ssl.py\", line 641, in do_handshake\n    self._sslobj.do_handshake()\nsocket.timeout: _ssl.c:704: The handshake operation timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/urllib_/urllib_.py\", line 15, in urlopen\n    with request.urlopen(url, data=data, timeout=8) as f:\n  File \"/usr/lib/python3.5/urllib/request.py\", line 163, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 466, in open\n    response = self._open(req, data)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 484, in _open\n    '_open', req)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 444, in _call_chain\n    result = func(*args)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1297, in https_open\n    context=self._context, check_hostname=self._check_hostname)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1256, in do_open\n    raise URLError(err)\nurllib.error.URLError: <urlopen error _ssl.c:704: The handshake operation timed out>",
        "levelname": "WARNING",
        "lineno": 22,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/urllib_/urllib_.py"
      },
      {
        "count": 1,
        "date": "2018-11-13T18:24:47.551057-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 311,
        "msg": "Download started.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-13T18:28:52.995513-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/home/pi/filefairy/util/urllib_/urllib_.py\", line 15, in urlopen\n    with request.urlopen(url, data=data, timeout=8) as f:\n  File \"/usr/lib/python3.5/urllib/request.py\", line 163, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 466, in open\n    response = self._open(req, data)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 484, in _open\n    '_open', req)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 444, in _call_chain\n    result = func(*args)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1297, in https_open\n    context=self._context, check_hostname=self._check_hostname)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1257, in do_open\n    r = h.getresponse()\n  File \"/usr/lib/python3.5/http/client.py\", line 1198, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.5/http/client.py\", line 297, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.5/http/client.py\", line 258, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"/usr/lib/python3.5/socket.py\", line 576, in readinto\n    return self._sock.recv_into(b)\n  File \"/usr/lib/python3.5/ssl.py\", line 937, in recv_into\n    return self.read(nbytes, buffer)\n  File \"/usr/lib/python3.5/ssl.py\", line 799, in read\n    return self._sslobj.read(len, buffer)\n  File \"/usr/lib/python3.5/ssl.py\", line 583, in read\n    v = self._sslobj.read(len, buffer)\nsocket.timeout: The read operation timed out",
        "levelname": "WARNING",
        "lineno": 22,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/urllib_/urllib_.py"
      },
      {
        "count": 92,
        "date": "2018-11-13T18:40:26.286907-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1254, in do_open\n    h.request(req.get_method(), req.selector, req.data, headers)\n  File \"/usr/lib/python3.5/http/client.py\", line 1107, in request\n    self._send_request(method, url, body, headers)\n  File \"/usr/lib/python3.5/http/client.py\", line 1152, in _send_request\n    self.endheaders(body)\n  File \"/usr/lib/python3.5/http/client.py\", line 1103, in endheaders\n    self._send_output(message_body)\n  File \"/usr/lib/python3.5/http/client.py\", line 934, in _send_output\n    self.send(msg)\n  File \"/usr/lib/python3.5/http/client.py\", line 877, in send\n    self.connect()\n  File \"/usr/lib/python3.5/http/client.py\", line 1253, in connect\n    super().connect()\n  File \"/usr/lib/python3.5/http/client.py\", line 849, in connect\n    (self.host,self.port), self.timeout, self.source_address)\n  File \"/usr/lib/python3.5/socket.py\", line 694, in create_connection\n    for res in getaddrinfo(host, port, 0, SOCK_STREAM):\n  File \"/usr/lib/python3.5/socket.py\", line 733, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\nsocket.gaierror: [Errno -3] Temporary failure in name resolution\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/urllib_/urllib_.py\", line 15, in urlopen\n    with request.urlopen(url, data=data, timeout=8) as f:\n  File \"/usr/lib/python3.5/urllib/request.py\", line 163, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 466, in open\n    response = self._open(req, data)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 484, in _open\n    '_open', req)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 444, in _call_chain\n    result = func(*args)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1297, in https_open\n    context=self._context, check_hostname=self._check_hostname)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1256, in do_open\n    raise URLError(err)\nurllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>",
        "levelname": "WARNING",
        "lineno": 22,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/urllib_/urllib_.py"
      },
      {
        "count": 2,
        "date": "2018-11-13T18:37:56.708191-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1254, in do_open\n    h.request(req.get_method(), req.selector, req.data, headers)\n  File \"/usr/lib/python3.5/http/client.py\", line 1107, in request\n    self._send_request(method, url, body, headers)\n  File \"/usr/lib/python3.5/http/client.py\", line 1152, in _send_request\n    self.endheaders(body)\n  File \"/usr/lib/python3.5/http/client.py\", line 1103, in endheaders\n    self._send_output(message_body)\n  File \"/usr/lib/python3.5/http/client.py\", line 934, in _send_output\n    self.send(msg)\n  File \"/usr/lib/python3.5/http/client.py\", line 877, in send\n    self.connect()\n  File \"/usr/lib/python3.5/http/client.py\", line 1253, in connect\n    super().connect()\n  File \"/usr/lib/python3.5/http/client.py\", line 849, in connect\n    (self.host,self.port), self.timeout, self.source_address)\n  File \"/usr/lib/python3.5/socket.py\", line 694, in create_connection\n    for res in getaddrinfo(host, port, 0, SOCK_STREAM):\n  File \"/usr/lib/python3.5/socket.py\", line 733, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\nsocket.gaierror: [Errno -3] Temporary failure in name resolution\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/urllib_/urllib_.py\", line 15, in urlopen\n    with request.urlopen(url, data=data, timeout=8) as f:\n  File \"/usr/lib/python3.5/urllib/request.py\", line 163, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 466, in open\n    response = self._open(req, data)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 484, in _open\n    '_open', req)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 444, in _call_chain\n    result = func(*args)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1297, in https_open\n    context=self._context, check_hostname=self._check_hostname)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1256, in do_open\n    raise URLError(err)\nurllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1254, in do_open\n    h.request(req.get_method(), req.selector, req.data, headers)\n  File \"/usr/lib/python3.5/http/client.py\", line 1107, in request\n    self._send_request(method, url, body, headers)\n  File \"/usr/lib/python3.5/http/client.py\", line 1152, in _send_request\n    self.endheaders(body)\n  File \"/usr/lib/python3.5/http/client.py\", line 1103, in endheaders\n    self._send_output(message_body)\n  File \"/usr/lib/python3.5/http/client.py\", line 934, in _send_output\n    self.send(msg)\n  File \"/usr/lib/python3.5/http/client.py\", line 877, in send\n    self.connect()\n  File \"/usr/lib/python3.5/http/client.py\", line 1253, in connect\n    super().connect()\n  File \"/usr/lib/python3.5/http/client.py\", line 849, in connect\n    (self.host,self.port), self.timeout, self.source_address)\n  File \"/usr/lib/python3.5/socket.py\", line 694, in create_connection\n    for res in getaddrinfo(host, port, 0, SOCK_STREAM):\n  File \"/usr/lib/python3.5/socket.py\", line 733, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\nsocket.gaierror: [Errno -3] Temporary failure in name resolution\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/urllib_/urllib_.py\", line 15, in urlopen\n    with request.urlopen(url, data=data, timeout=8) as f:\n  File \"/usr/lib/python3.5/urllib/request.py\", line 163, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 466, in open\n    response = self._open(req, data)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 484, in _open\n    '_open', req)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 444, in _call_chain\n    result = func(*args)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1297, in https_open\n    context=self._context, check_hostname=self._check_hostname)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1256, in do_open\n    raise URLError(err)\nurllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>",
        "levelname": "WARNING",
        "lineno": 22,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/urllib_/urllib_.py"
      },
      {
        "count": 2,
        "date": "2018-11-13T18:37:56.731817-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/home/pi/filefairy/util/slack/slack.py\", line 24, in _call\n    obj = json.loads(response)\n  File \"/usr/lib/python3.5/json/__init__.py\", line 319, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/lib/python3.5/json/decoder.py\", line 339, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/lib/python3.5/json/decoder.py\", line 357, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)",
        "levelname": "WARNING",
        "lineno": 26,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/slack/slack.py"
      },
      {
        "count": 1,
        "date": "2018-11-13T19:27:37.241196-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1254, in do_open\n    h.request(req.get_method(), req.selector, req.data, headers)\n  File \"/usr/lib/python3.5/http/client.py\", line 1107, in request\n    self._send_request(method, url, body, headers)\n  File \"/usr/lib/python3.5/http/client.py\", line 1152, in _send_request\n    self.endheaders(body)\n  File \"/usr/lib/python3.5/http/client.py\", line 1103, in endheaders\n    self._send_output(message_body)\n  File \"/usr/lib/python3.5/http/client.py\", line 934, in _send_output\n    self.send(msg)\n  File \"/usr/lib/python3.5/http/client.py\", line 877, in send\n    self.connect()\n  File \"/usr/lib/python3.5/http/client.py\", line 1261, in connect\n    server_hostname=server_hostname)\n  File \"/usr/lib/python3.5/ssl.py\", line 385, in wrap_socket\n    _context=self)\n  File \"/usr/lib/python3.5/ssl.py\", line 760, in __init__\n    self.do_handshake()\n  File \"/usr/lib/python3.5/ssl.py\", line 996, in do_handshake\n    self._sslobj.do_handshake()\n  File \"/usr/lib/python3.5/ssl.py\", line 641, in do_handshake\n    self._sslobj.do_handshake()\nsocket.timeout: _ssl.c:704: The handshake operation timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/urllib_/urllib_.py\", line 15, in urlopen\n    with request.urlopen(url, data=data, timeout=8) as f:\n  File \"/usr/lib/python3.5/urllib/request.py\", line 163, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 466, in open\n    response = self._open(req, data)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 484, in _open\n    '_open', req)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 444, in _call_chain\n    result = func(*args)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1297, in https_open\n    context=self._context, check_hostname=self._check_hostname)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1256, in do_open\n    raise URLError(err)\nurllib.error.URLError: <urlopen error _ssl.c:704: The handshake operation timed out>",
        "levelname": "WARNING",
        "lineno": 22,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/urllib_/urllib_.py"
      },
      {
        "count": 1,
        "date": "2018-11-13T20:00:28.656091-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['wget', 'https://www.orangeandblueleaguebaseball.com/StatsLab/league_file/orange_and_blue_league_baseball.tar.gz']' timed out after 4800 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['wget', 'https://www.orangeandblueleaguebaseball.com/StatsLab/league_file/orange_and_blue_league_baseball.tar.gz']' timed out after 4800 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-13T20:00:28.719156-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 299,
        "msg": "Download failed.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 17,
        "date": "2018-11-13T20:11:32.106837-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/home/pi/filefairy/util/statslab/statslab.py\", line 380, in parse_game_data\n    during=d)))\n  File \"/home/pi/filefairy/util/statslab/statslab.py\", line 140, in _value\n    bat = batters[batting]\nKeyError: ''",
        "levelname": "WARNING",
        "lineno": 488,
        "msg": "Unable to parse https://orangeandblueleaguebaseball.com/StatsLab/reports/news/html/game_logs/log_2164.html.",
        "pathname": "/home/pi/filefairy/util/statslab/statslab.py"
      },
      {
        "count": 17,
        "date": "2018-11-13T20:11:37.785545-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/home/pi/filefairy/util/statslab/statslab.py\", line 380, in parse_game_data\n    during=d)))\n  File \"/home/pi/filefairy/util/statslab/statslab.py\", line 140, in _value\n    bat = batters[batting]\nKeyError: ''",
        "levelname": "WARNING",
        "lineno": 488,
        "msg": "Unable to parse https://orangeandblueleaguebaseball.com/StatsLab/reports/news/html/game_logs/log_2184.html.",
        "pathname": "/home/pi/filefairy/util/statslab/statslab.py"
      },
      {
        "count": 17,
        "date": "2018-11-13T20:11:58.797024-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/home/pi/filefairy/util/statslab/statslab.py\", line 380, in parse_game_data\n    during=d)))\n  File \"/home/pi/filefairy/util/statslab/statslab.py\", line 140, in _value\n    bat = batters[batting]\nKeyError: ''",
        "levelname": "WARNING",
        "lineno": 488,
        "msg": "Unable to parse https://orangeandblueleaguebaseball.com/StatsLab/reports/news/html/game_logs/log_2218.html.",
        "pathname": "/home/pi/filefairy/util/statslab/statslab.py"
      },
      {
        "count": 2,
        "date": "2018-11-13T20:02:59.597620-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-13T20:04:04.757784-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 311,
        "msg": "Download started.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-13T20:07:04.487818-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1254, in do_open\n    h.request(req.get_method(), req.selector, req.data, headers)\n  File \"/usr/lib/python3.5/http/client.py\", line 1107, in request\n    self._send_request(method, url, body, headers)\n  File \"/usr/lib/python3.5/http/client.py\", line 1152, in _send_request\n    self.endheaders(body)\n  File \"/usr/lib/python3.5/http/client.py\", line 1103, in endheaders\n    self._send_output(message_body)\n  File \"/usr/lib/python3.5/http/client.py\", line 934, in _send_output\n    self.send(msg)\n  File \"/usr/lib/python3.5/http/client.py\", line 877, in send\n    self.connect()\n  File \"/usr/lib/python3.5/http/client.py\", line 1261, in connect\n    server_hostname=server_hostname)\n  File \"/usr/lib/python3.5/ssl.py\", line 385, in wrap_socket\n    _context=self)\n  File \"/usr/lib/python3.5/ssl.py\", line 760, in __init__\n    self.do_handshake()\n  File \"/usr/lib/python3.5/ssl.py\", line 996, in do_handshake\n    self._sslobj.do_handshake()\n  File \"/usr/lib/python3.5/ssl.py\", line 641, in do_handshake\n    self._sslobj.do_handshake()\nsocket.timeout: _ssl.c:704: The handshake operation timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/urllib_/urllib_.py\", line 15, in urlopen\n    with request.urlopen(url, data=data, timeout=8) as f:\n  File \"/usr/lib/python3.5/urllib/request.py\", line 163, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 466, in open\n    response = self._open(req, data)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 484, in _open\n    '_open', req)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 444, in _call_chain\n    result = func(*args)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1297, in https_open\n    context=self._context, check_hostname=self._check_hostname)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1256, in do_open\n    raise URLError(err)\nurllib.error.URLError: <urlopen error _ssl.c:704: The handshake operation timed out>",
        "levelname": "WARNING",
        "lineno": 22,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/urllib_/urllib_.py"
      },
      {
        "count": 1,
        "date": "2018-11-13T21:40:57.216569-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 289,
        "msg": "Restarted fairylab.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-13T21:40:57.875196-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded exports.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-13T21:40:58.029387-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded gameday.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-13T21:40:58.150065-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded git.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-13T21:40:58.274678-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded leaguefile.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-13T21:40:58.400664-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded recap.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-13T21:40:59.635306-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded snacks.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-13T21:40:59.765491-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded statsplus.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-13T21:41:37.362654-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 311,
        "msg": "Download started.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-13T22:10:21.391534-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 293,
        "msg": "Download finished.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-13T22:10:22.091090-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 64,
        "msg": "News updated.",
        "pathname": "/home/pi/filefairy/plugin/recap/recap.py"
      },
      {
        "count": 27,
        "date": "2018-11-13T22:11:12.664036-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/home/pi/filefairy/util/statslab/statslab.py\", line 380, in parse_game_data\n    during=d)))\n  File \"/home/pi/filefairy/util/statslab/statslab.py\", line 140, in _value\n    bat = batters[batting]\nKeyError: ''",
        "levelname": "WARNING",
        "lineno": 488,
        "msg": "Unable to parse /home/pi/filefairy/resource/extract/game_logs/log_2164.txt.",
        "pathname": "/home/pi/filefairy/util/statslab/statslab.py"
      },
      {
        "count": 27,
        "date": "2018-11-13T22:11:12.878976-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/home/pi/filefairy/util/statslab/statslab.py\", line 380, in parse_game_data\n    during=d)))\n  File \"/home/pi/filefairy/util/statslab/statslab.py\", line 140, in _value\n    bat = batters[batting]\nKeyError: ''",
        "levelname": "WARNING",
        "lineno": 488,
        "msg": "Unable to parse /home/pi/filefairy/resource/extract/game_logs/log_2184.txt.",
        "pathname": "/home/pi/filefairy/util/statslab/statslab.py"
      },
      {
        "count": 27,
        "date": "2018-11-13T22:11:13.112547-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/home/pi/filefairy/util/statslab/statslab.py\", line 380, in parse_game_data\n    during=d)))\n  File \"/home/pi/filefairy/util/statslab/statslab.py\", line 140, in _value\n    bat = batters[batting]\nKeyError: ''",
        "levelname": "WARNING",
        "lineno": 488,
        "msg": "Unable to parse /home/pi/filefairy/resource/extract/game_logs/log_2218.txt.",
        "pathname": "/home/pi/filefairy/util/statslab/statslab.py"
      }
    ]
  }
}
