{
  "records": {
    "2018-09-19T00:00:00-07:00": [
      {
        "count": 2,
        "date": "2018-09-19T00:47:18.578065-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 172,
        "msg": "Fetched latest changes.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 3,
        "date": "2018-09-19T00:56:06.417600-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 289,
        "msg": "Restarted fairylab.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 3,
        "date": "2018-09-19T00:56:06.849314-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded exports.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 4,
        "date": "2018-09-19T00:56:06.906147-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded gameday.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 3,
        "date": "2018-09-19T00:56:06.943578-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded git.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 3,
        "date": "2018-09-19T00:56:06.984257-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded leaguefile.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 3,
        "date": "2018-09-19T00:56:07.028347-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded recap.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 3,
        "date": "2018-09-19T00:56:08.135418-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded snacks.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 3,
        "date": "2018-09-19T00:56:08.174553-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded statsplus.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-09-19T00:49:04.103151-07:00",
        "exc": "Traceback (most recent call last):\n  File \"core/fairylab/fairylab.py\", line 114, in _try\n    response = item(*args, **dict(kwargs, date=date))\n  File \"/home/pi/filefairy/api/registrable/registrable.py\", line 76, in _notify\n    response = self._notify_internal(**kwargs)\n  File \"/home/pi/filefairy/plugin/git/git.py\", line 61, in _notify_internal\n    self.automate('fairylab', **kwargs)\n  File \"/home/pi/filefairy/plugin/git/git.py\", line 153, in automate\n    sub = self.push(*args, **kwargs)\n  File \"/home/pi/filefairy/plugin/git/git.py\", line 178, in push\n    response = self._call(['git', 'push'], *args, **kwargs)\n  File \"/home/pi/filefairy/plugin/git/git.py\", line 120, in _call\n    output = check_output(cmd)\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1446, in _communicate\n    ready = selector.select(timeout)\n  File \"/usr/lib/python3.5/selectors.py\", line 376, in select\n    fd_event_list = self._poll.poll(timeout)\nKeyboardInterrupt",
        "levelname": "INFO",
        "lineno": 127,
        "msg": "Disabled git.",
        "pathname": "/home/pi/fairylab/static/core/fairylab/fairylab.py"
      }
    ],
    "2018-09-20T00:00:00-07:00": [
      {
        "count": 1,
        "date": "2018-09-20T00:01:09.759814-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 184,
        "msg": "Automated push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      }
    ],
    "2018-09-21T00:00:00-07:00": [
      {
        "count": 1,
        "date": "2018-09-21T00:01:07.012790-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 184,
        "msg": "Automated push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-09-21T18:12:54.952381-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 194,
        "msg": "Tracker locked.",
        "pathname": "/home/pi/filefairy/plugin/exports/exports.py"
      },
      {
        "count": 1,
        "date": "2018-09-21T20:13:53.069710-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 107,
        "msg": "Upload started.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      }
    ],
    "2018-09-22T00:00:00-07:00": [
      {
        "count": 1,
        "date": "2018-09-22T00:00:54.603416-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 184,
        "msg": "Automated push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-09-22T02:22:44.391828-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 315,
        "msg": "File is up.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-09-22T02:22:44.912429-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 309,
        "msg": "Download started.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-09-22T02:27:30.953955-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 291,
        "msg": "Download finished.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-09-22T02:27:31.444882-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 63,
        "msg": "News updated.",
        "pathname": "/home/pi/filefairy/plugin/recap/recap.py"
      }
    ],
    "2018-09-23T00:00:00-07:00": [
      {
        "count": 1,
        "date": "2018-09-23T00:00:11.950042-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 184,
        "msg": "Automated push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-09-23T16:30:23.835677-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 194,
        "msg": "Tracker locked.",
        "pathname": "/home/pi/filefairy/plugin/exports/exports.py"
      },
      {
        "count": 1,
        "date": "2018-09-23T18:09:14.714009-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 107,
        "msg": "Upload started.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-09-23T20:25:44.727216-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 315,
        "msg": "File is up.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-09-23T20:25:46.245462-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 309,
        "msg": "Download started.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-09-23T20:34:15.170579-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 291,
        "msg": "Download finished.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-09-23T20:34:16.807065-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 63,
        "msg": "News updated.",
        "pathname": "/home/pi/filefairy/plugin/recap/recap.py"
      }
    ],
    "2018-09-24T00:00:00-07:00": [
      {
        "count": 2,
        "date": "2018-09-24T21:32:12.908678-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 289,
        "msg": "Restarted fairylab.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 2,
        "date": "2018-09-24T21:32:13.354058-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded exports.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-09-24T21:31:18.281589-07:00",
        "exc": "Traceback (most recent call last):\n  File \"core/fairylab/fairylab.py\", line 262, in _install\n    instance = plugin(date=date, e=self.environment)\n  File \"/home/pi/filefairy/plugin/gameday/gameday.py\", line 35, in __init__\n    super().__init__(**kwargs)\n  File \"/home/pi/filefairy/api/registrable/registrable.py\", line 23, in __init__\n    super().__init__(**kwargs)\n  File \"/home/pi/filefairy/api/messageable/messageable.py\", line 23, in __init__\n    super().__init__(**kwargs)\n  File \"/home/pi/filefairy/api/renderable/renderable.py\", line 29, in __init__\n    super().__init__(**kwargs)\n  File \"/home/pi/filefairy/api/serializable/serializable.py\", line 26, in __init__\n    self.read()\n  File \"/home/pi/filefairy/api/serializable/serializable.py\", line 37, in read\n    self.data = json.loads(f.read())\n  File \"/usr/lib/python3.5/json/__init__.py\", line 319, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/lib/python3.5/json/decoder.py\", line 339, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/lib/python3.5/json/decoder.py\", line 355, in raw_decode\n    obj, end = self.scan_once(s, idx)\njson.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 12 column 1 (char 129)",
        "levelname": "INFO",
        "lineno": 268,
        "msg": "Disabled gameday.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 2,
        "date": "2018-09-24T21:32:13.542626-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded git.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 2,
        "date": "2018-09-24T21:32:13.597211-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded leaguefile.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 2,
        "date": "2018-09-24T21:32:13.653890-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded recap.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 2,
        "date": "2018-09-24T21:32:14.772449-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded snacks.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 2,
        "date": "2018-09-24T21:32:14.825036-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded statsplus.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-09-24T21:31:35.789400-07:00",
        "exc": "Traceback (most recent call last):\n  File \"core/fairylab/fairylab.py\", line 114, in _try\n    response = item(*args, **dict(kwargs, date=date))\n  File \"/home/pi/filefairy/api/registrable/registrable.py\", line 76, in _notify\n    response = self._notify_internal(**kwargs)\n  File \"/home/pi/filefairy/plugin/git/git.py\", line 61, in _notify_internal\n    self.automate('fairylab', **kwargs)\n  File \"/home/pi/filefairy/plugin/git/git.py\", line 153, in automate\n    sub = self.push(*args, **kwargs)\n  File \"/home/pi/filefairy/plugin/git/git.py\", line 178, in push\n    response = self._call(['git', 'push'], *args, **kwargs)\n  File \"/home/pi/filefairy/plugin/git/git.py\", line 120, in _call\n    output = check_output(cmd)\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1446, in _communicate\n    ready = selector.select(timeout)\n  File \"/usr/lib/python3.5/selectors.py\", line 376, in select\n    fd_event_list = self._poll.poll(timeout)\nKeyboardInterrupt",
        "levelname": "INFO",
        "lineno": 127,
        "msg": "Disabled git.",
        "pathname": "/home/pi/fairylab/static/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-09-24T21:32:13.452496-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded gameday.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      }
    ],
    "2018-09-25T00:00:00-07:00": [
      {
        "count": 1,
        "date": "2018-09-25T00:00:55.133006-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 184,
        "msg": "Automated push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-09-25T00:31:38.149619-07:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-09-25T06:43:49.120763-07:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-09-25T09:16:35.148811-07:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-09-25T11:54:07.751931-07:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-09-25T13:55:06.309076-07:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-09-25T18:39:09.844415-07:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-09-25T18:47:29.130860-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 194,
        "msg": "Tracker locked.",
        "pathname": "/home/pi/filefairy/plugin/exports/exports.py"
      },
      {
        "count": 1,
        "date": "2018-09-25T19:02:36.914264-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 155,
        "msg": "Sim in progress.",
        "pathname": "/home/pi/filefairy/plugin/statsplus/statsplus.py"
      },
      {
        "count": 15280,
        "date": "2018-09-25T23:00:55.988760-07:00",
        "exc": "Traceback (most recent call last):\n  File \"/home/pi/filefairy/util/urllib_/urllib_.py\", line 14, in urlopen\n    with request.urlopen(url, data=data, timeout=8) as f:\n  File \"/usr/lib/python3.5/urllib/request.py\", line 163, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 472, in open\n    response = meth(req, response)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 582, in http_response\n    'http', request, response, code, msg, hdrs)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 510, in error\n    return self._call_chain(*args)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 444, in _call_chain\n    result = func(*args)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 590, in http_error_default\n    raise HTTPError(req.full_url, code, msg, hdrs, fp)\nurllib.error.HTTPError: HTTP Error 403: Forbidden",
        "levelname": "WARNING",
        "lineno": 17,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/urllib_/urllib_.py"
      },
      {
        "count": 233,
        "date": "2018-09-25T19:18:37.682666-07:00",
        "exc": "Traceback (most recent call last):\n  File \"/home/pi/filefairy/util/urllib_/urllib_.py\", line 14, in urlopen\n    with request.urlopen(url, data=data, timeout=8) as f:\n  File \"/usr/lib/python3.5/urllib/request.py\", line 163, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 472, in open\n    response = meth(req, response)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 582, in http_response\n    'http', request, response, code, msg, hdrs)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 510, in error\n    return self._call_chain(*args)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 444, in _call_chain\n    result = func(*args)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 590, in http_error_default\n    raise HTTPError(req.full_url, code, msg, hdrs, fp)\nurllib.error.HTTPError: HTTP Error 404: Not Found",
        "levelname": "WARNING",
        "lineno": 17,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/urllib_/urllib_.py"
      },
      {
        "count": 1,
        "date": "2018-09-25T19:39:42.249751-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 107,
        "msg": "Upload started.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-09-25T19:51:14.918825-07:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-09-25T21:27:07.786032-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 315,
        "msg": "File is up.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-09-25T21:27:08.269121-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 309,
        "msg": "Download started.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-09-25T22:07:13.181186-07:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1254, in do_open\n    h.request(req.get_method(), req.selector, req.data, headers)\n  File \"/usr/lib/python3.5/http/client.py\", line 1107, in request\n    self._send_request(method, url, body, headers)\n  File \"/usr/lib/python3.5/http/client.py\", line 1152, in _send_request\n    self.endheaders(body)\n  File \"/usr/lib/python3.5/http/client.py\", line 1103, in endheaders\n    self._send_output(message_body)\n  File \"/usr/lib/python3.5/http/client.py\", line 934, in _send_output\n    self.send(msg)\n  File \"/usr/lib/python3.5/http/client.py\", line 877, in send\n    self.connect()\n  File \"/usr/lib/python3.5/http/client.py\", line 1253, in connect\n    super().connect()\n  File \"/usr/lib/python3.5/http/client.py\", line 849, in connect\n    (self.host,self.port), self.timeout, self.source_address)\n  File \"/usr/lib/python3.5/socket.py\", line 712, in create_connection\n    raise err\n  File \"/usr/lib/python3.5/socket.py\", line 703, in create_connection\n    sock.connect(sa)\nOSError: [Errno 101] Network is unreachable\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/urllib_/urllib_.py\", line 14, in urlopen\n    with request.urlopen(url, data=data, timeout=8) as f:\n  File \"/usr/lib/python3.5/urllib/request.py\", line 163, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 466, in open\n    response = self._open(req, data)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 484, in _open\n    '_open', req)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 444, in _call_chain\n    result = func(*args)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1297, in https_open\n    context=self._context, check_hostname=self._check_hostname)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1256, in do_open\n    raise URLError(err)\nurllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>",
        "levelname": "WARNING",
        "lineno": 17,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/urllib_/urllib_.py"
      },
      {
        "count": 1,
        "date": "2018-09-25T23:24:48.528539-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 289,
        "msg": "Restarted fairylab.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-09-25T23:24:48.977563-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded exports.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-09-25T23:24:49.044187-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded gameday.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-09-25T23:24:49.103470-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded git.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-09-25T23:24:49.188373-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded leaguefile.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-09-25T23:24:49.255222-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded recap.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-09-25T23:24:50.444259-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded snacks.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-09-25T23:24:50.508566-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded statsplus.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-09-25T23:25:03.423938-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 309,
        "msg": "Download started.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-09-25T23:33:04.762303-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 291,
        "msg": "Download finished.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-09-25T23:33:08.324183-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 63,
        "msg": "News updated.",
        "pathname": "/home/pi/filefairy/plugin/recap/recap.py"
      },
      {
        "count": 1,
        "date": "2018-09-25T23:39:09.425926-07:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      }
    ]
  }
}
